### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by stigok** [sl1pm4t/terraform-provider-kubernetes#10]
I was spending some time figuring out how to use locally built providers. The readme does indeed show how to build the solution, but it's using example path names instead of this fork's name

    cd $GOPATH/src/github.com/terraform-providers/terraform-provider-$PROVIDER_NAME

Will updating the readme have any other unwanted implications, or should I take the time to update it with some more accurate info?

Additionally, I want to add some info about `terraform init plugin-dir="$(go env GOPATH)"`

**Comment by sl1pm4t** [comment]
Hi @stigok I updated the README with some of the details you mention above.
Please feel free to send a PR for any other info you think is helpful.

**Comment by stigok** [comment]
My exact thoughts! LGTM ;)

**Comment by nover** [comment]
@stigok @sl1pm4t total Terraform noob here trying to recreate an existing kubernetes cluster setup with Terraform, and I need to define ingress rules, so I found this fork of the module :)

However, I do not think it's clear from the readme, how you actually go about building _and_ using this forked module. Would any of you care to explain it to me / update the README? Thanks!

**Comment by stigok** [comment]
@nover you can take a sneak-peek in my PR.

**Comment by stigok** [comment]
Merged 637ff28

**Comment by jakubknejzlik** [comment]
@stigok how could I use this fork with other provider (eg. digitalocean). The thing is that I run `terraform init -plugin-dir=$GOPATH/bin` which installs the kubernetes fork but fails to install other providers. But running `terraform init` to download the official providers (like this digitalocean) it overrides kubernetes provider fork :-/ .
Any ideas or suggestions?

**Comment by jakubknejzlik** [comment]
Ok, nevermind. Actually placing the binary to plugins folder manually forces the terraform to skip the initialization (in my case macos -> `.terraform/plugins/darwin_amd64/terraform-provider-kubernetes`)
