### ISSUE TITLE
StatefulSet update strategy not propagating

### ISSUE THREAD

**Issue by stigok** [sl1pm4t/terraform-provider-kubernetes#13]
### Terraform Version
0.11.7

### Affected Resource(s)
- kubernetes_stateful_set

### Terraform Configuration Files
```hcl
provider "kubernetes" {}

resource kubernetes_namespace "default" {
  metadata {
    name = "tkp-test"
  }
}

resource kubernetes_stateful_set "ingestor" {
  metadata {
    name = "pingers"
    namespace = "${kubernetes_namespace.default.metadata.0.name}"
  }

  spec {
    selector {
      app = "pinger"
    }

    service_name = "pinger"

    update_strategy {
      type = "RollingUpdate"
    }

    replicas = 2

    template {
      metadata {
        labels {
          app = "pinger"
        }
      }

      spec {
        termination_grace_period_seconds = 5

        container {
          name = "pinger-a"
          image = "debian:buster"
          command = ["ping", "github.com"]
        }
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/stigok/b7133efd7a5dec635ab9747312b871f5

### Expected Behavior
`update_strategy` actually sets the StatefulSet's update strategy.

### Actual Behavior
The value of `update_strategy` is not actually set on the cluster. The default is used instead, which is `OnDelete`.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### Important Factoids
Google Cloud Engine managed cluster

**Comment by sl1pm4t** [comment]
Thanks @stigok I'll take a look.
