### ISSUE TITLE
Updating internal annotation fails.

### ISSUE THREAD

**Issue by Phylu** [sl1pm4t/terraform-provider-kubernetes#2]
Hi there,

Updating an internal annotation fails.

### Terraform Version
- Terraform v0.11.3
- provider.kubernetes (unversioned) commit: 32a278b7b336590fab8660ce35b21efea9fc601f

### Affected Resource(s)
- kubernetes_service

### Terraform Configuration Files
```hcl
resource "kubernetes_service" "svc" {
  metadata {
    name = "svc"
    namespace = "namespace"
    labels {
        app = "svc"
    }
    annotations {
        "service.beta.kubernetes.io/aws-load-balancer-internal" = "0.0.0.0/0"
    }
  }
  spec {
    type = "LoadBalancer"
    port {
        port = 80
        target_port = 80
        name = "http"
    }
  }
}
```

### Expected Behavior
Re-running `terraform apply` after adding the internal annotation should add the annotation to the kubernetes service
```
  ~ kubernetes_service.svc
      metadata.0.annotations.%:                                                     "0" => "1"
      metadata.0.annotations.service.beta.kubernetes.io/aws-load-balancer-internal: "" => "0.0.0.0/0"
```

### Actual Behavior
The command fails with the error message:
```
* kubernetes_service.svc: 1 error(s) occurred:
* kubernetes_service.svc: Failed to update service: jsonpatch add operation does not apply: doc is missing path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-internal
```

### Steps to Reproduce
1. `terraform apply`

### References
I thought this should not be a problem due to the PR:
- https://github.com/terraform-providers/terraform-provider-kubernetes/pull/40

**Comment by sl1pm4t** [comment]
Thanks @Phylu - I agree, likely the same problem as the issue you reference.
I also hit this myself this week and have been meaning to investigate.

**Comment by Phylu** [comment]
I think this comment https://github.com/terraform-providers/terraform-provider-kubernetes/issues/37#issue-246021533 explains the issue even better that I did and even makes a suggestion on how to fix it.

**Comment by acobaugh** [comment]
I think upstream just fixed this via https://github.com/terraform-providers/terraform-provider-kubernetes/pull/116

**Comment by Phylu** [comment]
I just cherry-picked the commits from the upstream repository and can confirm that I don't get anymore errors on update. @sl1pm4t Do you want to sync from upstream? Or shall I create a PR containing the change.

**Comment by sl1pm4t** [comment]
Thanks for testing it @Phylu.
I've just rebased the custom branch on upstream master, and pushed to this repo, so it should include the fix now.

**Comment by Phylu** [comment]
I can confirm that it works. Thanks a lot!
