### ISSUE TITLE
Use affinity and tolerations with DaemonSet

### ISSUE THREAD

**Issue by abagshaw** [sl1pm4t/terraform-provider-kubernetes#26]
Am I able to use `affinity` and `tolerations` properties for DaemonSets with this provider? I'm getting an error when I try to do so:

```
Error: kubernetes_daemonset.mydaemon: spec.0.template.0.spec.0: invalid or unknown key: affinity
```

```
Error: kubernetes_daemonset.mydaemon: spec.0.template.0.spec.0: invalid or unknown key: toleration
```

**Comment by sl1pm4t** [comment]
Hi @abagshaw - these attributes have not been added to the resource schema's yet.

**Comment by sl1pm4t** [comment]
@abagshaw - tolerations have been added in #59
