### ISSUE TITLE
Support ClusterRole, Role, RoleBinding ClusterRoleBinding

### ISSUE THREAD

**Issue by geoffsimba** [sl1pm4t/terraform-provider-kubernetes#35]
It would be awesome if you could support the above resources as well, as they are used in the standard setups of an ingress controller such as nginx-ingress. (since Ingress is already supported)

see https://github.com/kubernetes/ingress-nginx
and see the Mandatory Command in https://kubernetes.github.io/ingress-nginx/deploy/

Thanks for the great work! Makes terraform actually remotely usable unlike the core provider version.

**Comment by sl1pm4t** [comment]
Closed by #39
