### ISSUE TITLE
New Feature request: NetworkPolicy support

### ISSUE THREAD

**Issue by lainra** [sl1pm4t/terraform-provider-kubernetes#46]
Hi everyone,

I came here from the official terraform-providers/terraform-provider-kubernetes repository, sadly learning it was not maintained anymore.
I wish to ask you if there is any chance you could work on the NetworkPolicy resource implementation?
There is existing work in the former repo which hasn't be merged yet.

https://github.com/terraform-providers/terraform-provider-kubernetes/issues/110
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/113
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/118

In the worst case, I would have to do it myself, but i'm far from being a beast so it could take quite long. If I could have at least a quick estimation of the level of work, I could take some actions (either praying or struggling :) )

Thanks,

Sincerely,

Raphael

**Comment by sl1pm4t** [comment]
Hi @lainra - thanks for the suggestion. Once I've got some spare cycles I'll look into this one.

**Comment by TheMacStack** [comment]
With the AKS / Calico integrations coming soon (~end of November) and with it native NetworkPolicy support for AKS I would be very happy to see NetworkPolicy support on this fork. 

Keep up the good work.
