### ISSUE TITLE
kubeconfig created by a Terraform resource

### ISSUE THREAD

**Issue by gaui** [sl1pm4t/terraform-provider-kubernetes#47]
When kubeconfig is created by a Terraform resource, the cluster connection fails for the first time. Probably because the kubeconfig is read initially, before the Terraform resource creates it and flushes it to disk. This makes the process fail the first time with the following message:

```
module.vsphere.module.cluster.module.kubernetes.module.rke.local_file.kubeconfig: Creation complete after 0s (ID: 3e86743804c08d5312c04e5f299b270d07f198a2)
module.vsphere.module.cluster.module.kubernetes.module.rke.data.local_file.kubeconfig: Refreshing state...
module.vsphere.module.cluster.module.kubernetes.module.some.null_resource.kube_triggers: Creating...
module.vsphere.module.cluster.module.kubernetes.module.some.kubernetes_namespace.some_namespace: Creating...

Error: Error applying plan:

1 error(s) occurred:

* module.vsphere.module.cluster.module.kubernetes.module.some.kubernetes_namespace.some_namespace: 1 error(s) occurred:

* kubernetes_namespace.some_namespace: Post http://localhost/api/v1/namespaces: dial tcp 127.0.0.1:80: connect: connection refused
```

Would it be possible to change the behavior so either:

- Each Kubernetes resource reads the kubeconfig when run, not the provider initially.
- Provide the ability to input the config as a string as an argument to the resources, so I would just use the Terraform variable (it contains the config as a string).
- Other possible method?

### Terraform Version
0.11.8

### Affected Resource(s)
- kubernetes_*

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* module.vsphere.module.cluster.module.kubernetes.module.some.kubernetes_namespace.some_namespace: 1 error(s) occurred:

* kubernetes_namespace.some_namespace: Post http://localhost/api/v1/namespaces: dial tcp 127.0.0.1:80: connect: connection refused
```

### Expected Behavior
It should be able to connect to the Kubernetes cluster.

### Actual Behavior
kubeconfig is created by a Terraform resource and flushed to disk, so the Kubernetes provider doesn't find the config (because it's read in the beginning probably), until running `terraform apply` the second time.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by sl1pm4t** [comment]
As I understand it, this is a problem in Terraform core. 
See https://github.com/hashicorp/terraform/issues/2430 for details.

One way we've tackled this problem is by splitting up our Terraform config.
We have an "infrastructure" config that deploys base infrastructure (such as Kubernetes clusters), and then a separate "app" config to deploy the Kubernetes resources. 
The app config reads Kubernetes connections details from the infra config via a `terraform_remote_state` datasource.

**Comment by gaui** [comment]
@sl1pm4t Yeah exactly how I solved it at first, but then I discovered I can initialize providers at the same level as my "create cluster resource", so I can do...

```
resource rke_cluster "cluster" {
  nodes = [
    {
      address = "1.2.3.4"
      user    = "ubuntu"
      role    = ["controlplane", "worker", "etcd"]
      ssh_key = "${file("~/.ssh/id_rsa")}"
    },
  ]
}

provider "kubernetes" {
  host     = "${rke_cluster.cluster.api_server_url}"
  username = "${rke_cluster.cluster.kube_admin_user}"

  client_certificate     = "${rke_cluster.cluster.client_cert}"
  client_key             = "${rke_cluster.cluster.client_key}"
  cluster_ca_certificate = "${rke_cluster.cluster.ca_crt}"
  # load_config_file = false
}

resource "kubernetes_namespace" "example" {
  metadata {
    name = "terraform-example-namespace"
  }
}

# for running kubectl
resource "local_file" kubeconfig {
  filename = "${path.root}/kubeconfig"
  content  = "${rke_cluster.rke_cluster.kube_config_yaml}"
}
```

**Comment by gaui** [comment]
Gonna close this because this is not an issue with this provider. 😄
