### ISSUE TITLE
Using imagePullSecrets to pull container from a private repository

### ISSUE THREAD

**Issue by Phylu** [sl1pm4t/terraform-provider-kubernetes#5]
Hi there,

Using imagePullSecrets to pull a container from a private repository does not seem to work.

### Terraform Version
- Terraform v0.11.3
- provider.kubernetes (unversioned) commit: 01eb52b7c6b615b945e7deda48184dafef53e292

### Affected Resource(s)
- kubernetes_deployment

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "application" {
  metadata {
    name = "application"
    namespace = "namespace"
  }

  spec {
    selector {
      app = "application"
    }

    template {
      metadata {
        labels {
          app = "application"
        }
      }

      spec {

        container {
          name  = "application"
          image = "docker-private.example.org/application:latest"

          port {
            container_port = 3000
          }
        }

        imagePullSecrets {
          name = "secret"
        }

      }
    }
  }
}
```

### Expected Behavior
Running `terraform apply` should apply the deployment.

### Actual Behavior
The command fails with the error message:
```
Error: module.juice-shop.kubernetes_deployment.juice-shop: spec.0.template.0.spec.0: invalid or unknown key: imagePullSecrets
```

### Steps to Reproduce
1. `terraform apply`

**Comment by sl1pm4t** [comment]
Hi @Phylu - try `image_pull_secret` instead.

**Comment by Phylu** [comment]
Thanks. It is nearly working. `image_pull_secrets` (with an s) is correct. Is there a good way to document these things? 
My go knowledge is currently not sufficient to help with the code, but I am happy to give some support on those things, if it is helpful.
