### ISSUE TITLE
Add field "revision_history_limit" to Deployment schema

### ISSUE THREAD

**Issue by dominik-lekse** [sl1pm4t/terraform-provider-kubernetes#7]
First of all thanks this fork and the support of next gen K8s resources in Terraform.

One minor: Could you add the field `revision_history_limit` to the schema of `Deployment`? Looks like it is already supported in `func expandDeploymentSpec` but not yet in the schema and in `func flattenDeploymentSpec`.

**Comment by sl1pm4t** [comment]
@dominik-lekse this field has been added to the `Deployment` schema.

**Comment by dominik-lekse** [comment]
@sl1pm4t Many thanks.
